### ISSUE TITLE
Consider publishing as a dotnet tool

### ISSUE THREAD

**Issue by baronfel** [MokoSan/FSharpAdvent_2021#1]
If you add the following to your tool's project file:

```xml
<PackAsTool>true</PackAsTool>
<ToolCommandName>perfavore</ToolCommandName> <!-- feel free to use whatever name you like -->
```

then run `dotnet pack`, then the tool will be published as a [dotnet tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools).  This allows users to install the tool via `dotnet tool install <tool name>` and run it via `dotnet <tool name>`, which could be great for distribution and ease of use!

**Comment by MokoSan** [comment]
@baronfel - Thanks! Will give this a shot soon. 

EDIT: This is up [here](https://www.nuget.org/packages/PerfAvore/).. Now I got an incentive to improve this beyond the scope of the F# Advent. :p - thanks for your help!

**Comment by baronfel** [comment]
Heck yeah! Dotnet tools are great for things like this, they really simplify distribution. If you run into any things you're missing from dotnet tools that you'd like to see, I'd love to hear about them - I'll get them on the backlog for triage by the team.

**Comment by MokoSan** [comment]
Absolutely - will do! Thanks again. I remember your Open FSharp 2019 presentation re: Performance + F# was definitely a memorable one. Best,
